apiVersion: v1
kind: Pod
metadata:
  name: test-mysql
  labels:
    app: test-mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "testpassword123"
    - name: MYSQL_DATABASE
      value: "testdb"
    ports:
    - containerPort: 3306
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: test-mysql
spec:
  selector:
    app: test-mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
